[package]
name = "moodle-session-ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }

kv = { path = "../rust-kv", features = ["bincode-value", "json-value"] }
serde = "1.0.143"
serde_millis = "0.1.1"
bincode = "1.3.3"

tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
anyhow = "1.0.62"
camino = "1.1.1"