apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-session-ext
spec:
  replicas: 1
  revisionHistoryLimit: 0 # we use a PVC for the DB, so we can't keep old revisions
  selector:
    matchLabels:
      app: moodle-session-ext
  template:
    metadata:
      labels:
        app: moodle-session-ext
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      containers:
        - name: moodle-session-ext
          image: ghcr.io/dcnick3/moodle-session-ext:ref-cefae23f6dc152f5b32eb558ab547985ae7daa98
          volumeMounts:
            - mountPath: /sessions.db
              name: sessions-storage
          env:
            - name: RUST_LOG
              value: "info,moodle_session_ext=trace"
      volumes:
        - name: sessions-storage
          persistentVolumeClaim:
            claimName: moodle-session-ext-pvc